### ISSUE TITLE
Don't adjust center and zoom when set in URL

### ISSUE THREAD

**Issue by Schpidi** [geotiffjs/cog-explorer#9]

**Comment by cholmes** [comment]
+1 - just hit this myself, was about to file an issue. It's really nice to drop a URL to someone of exactly what you're looking at, and was going to do that but it zoomed out to the overview. 

Ended up not tweeting https://geotiffjs.github.io/cog-explorer/#long=-95.832&lat=29.779&zoom=14&scene=https://storage.googleapis.com/pdd-stac/disasters/hurricane-harvey/0831/Harvey-20170831-1040-102e-1044-RGB.tif&pipeline= because the overview is a bit shitty, even though the detail I tried to link to is great.

**Comment by constantinius** [comment]
Okay, this is now fixed.

**Comment by cholmes** [comment]
awesome. The tweet that I put out now goes to the right place! Thanks for the quick fix.
